version: "3.7"

services:
    repro:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - uwsgibug
        expose:
            - 8000
        ports:
            - 8089:8000
        # environment:
        #     MODULE: 'flask_app:app'

    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        expose:
            - 80
        ports:
            - 8088:80
        networks:
            - uwsgibug
        depends_on:
            - repro

networks:
    uwsgibug: